kind: pipeline
type: docker
name: default

workspace:
  base: /go
  path: src/github.com/one-byte-data/${DRONE_REPO_NAME}

trigger:
  event:
    - push
    - pull_request
    - tag
    
steps:
  - name: test
    image: golang:latest
    commands:
      - go test -coverprofile=coverage.txt ./...

  - name: build
    image: golang:latest
    environment:
      CGO_ENABLED: "0"
      GOOS: linux
      GOARCH: amd64
    commands:
      - go build -v -a -ldflags "-X main.version=build.${DRONE_BUILD_NUMBER}" -o build/docker/ci-kubernetes

  - name: docker-dev
    image: plugins/docker
    when:
      branch:
        - main
      event:
        - push
    settings:
      username:
        from_secret: github_username
      password:
        from_secret: github_password
      registry: ghcr.io
      repo: ghcr.io/one-byte-data/${DRONE_REPO_NAME}
      tags:
        - dev

  - name: docker-latest
    image: plugins/docker
    when:
      branch:
        - main
      event:
        - tag
    settings:
      username:
        from_secret: github_username
      password:
        from_secret: github_password
      registry: ghcr.io
      repo: ghcr.io/one-byte-data/${DRONE_REPO_NAME}
      tags:
        - latest
        - ${DRONE_TAG}

  - name: docker-public
    image: plugins/docker
    when:
      branch:
        - main
      event:
        - tag
    settings:
      username: deyung
      password:
        from_secret: dockerhub_token
      repo: deyung/${DRONE_REPO_NAME}
      tags:
        - latest
        - ${DRONE_TAG}
